/**
 * The composite tenant foreign keys of audit M3.
 *
 * Each child row's (tenant_id, column) must name a parent row of the same
 * tenant. Shared by the integrity check and its test, which also asserts each
 * list matches its migration exactly.
 */

/** Learning, money and access paths (migrations 120 and 121). */
export const CORE_TENANT_FOREIGN_KEYS = [
  {
    child: "course_modules",
    column: "course_id",
    parent: "courses",
    name: "course_modules_course_id_tenant_fkey",
  },
  {
    child: "lessons",
    column: "module_id",
    parent: "course_modules",
    name: "lessons_module_id_tenant_fkey",
  },
  {
    child: "lesson_assets",
    column: "lesson_id",
    parent: "lessons",
    name: "lesson_assets_lesson_id_tenant_fkey",
  },
  {
    child: "lesson_progress",
    column: "lesson_id",
    parent: "lessons",
    name: "lesson_progress_lesson_id_tenant_fkey",
  },
  {
    child: "lesson_progress",
    column: "membership_id",
    parent: "memberships",
    name: "lesson_progress_membership_id_tenant_fkey",
  },
  {
    child: "enrollments",
    column: "course_id",
    parent: "courses",
    name: "enrollments_course_id_tenant_fkey",
  },
  {
    child: "enrollments",
    column: "membership_id",
    parent: "memberships",
    name: "enrollments_membership_id_tenant_fkey",
  },
  {
    child: "assessment_items",
    column: "assessment_id",
    parent: "assessments",
    name: "assessment_items_assessment_id_tenant_fkey",
  },
  {
    child: "assessment_items",
    column: "item_id",
    parent: "items",
    name: "assessment_items_item_id_tenant_fkey",
  },
  {
    child: "item_options",
    column: "item_id",
    parent: "items",
    name: "item_options_item_id_tenant_fkey",
  },
  {
    child: "attempts",
    column: "assessment_id",
    parent: "assessments",
    name: "attempts_assessment_id_tenant_fkey",
  },
  {
    child: "attempts",
    column: "membership_id",
    parent: "memberships",
    name: "attempts_membership_id_tenant_fkey",
  },
  {
    child: "attempt_answers",
    column: "attempt_id",
    parent: "attempts",
    name: "attempt_answers_attempt_id_tenant_fkey",
  },
  {
    child: "attempt_answers",
    column: "assessment_item_id",
    parent: "assessment_items",
    name: "attempt_answers_assessment_item_id_tenant_fkey",
  },
  {
    child: "grading_tasks",
    column: "attempt_id",
    parent: "attempts",
    name: "grading_tasks_attempt_id_tenant_fkey",
  },
  {
    child: "proctoring_sessions",
    column: "attempt_id",
    parent: "attempts",
    name: "proctoring_sessions_attempt_id_tenant_fkey",
  },
  {
    child: "proctoring_sessions",
    column: "membership_id",
    parent: "memberships",
    name: "proctoring_sessions_membership_id_tenant_fkey",
  },
  {
    child: "proctoring_events",
    column: "proctoring_session_id",
    parent: "proctoring_sessions",
    name: "proctoring_events_proctoring_session_id_tenant_fkey",
  },
  {
    child: "certificates",
    column: "membership_id",
    parent: "memberships",
    name: "certificates_membership_id_tenant_fkey",
  },
  {
    child: "certificate_wallet_passes",
    column: "certificate_id",
    parent: "certificates",
    name: "certificate_wallet_passes_certificate_id_tenant_fkey",
  },
  {
    child: "credential_verifications",
    column: "certificate_id",
    parent: "certificates",
    name: "credential_verifications_certificate_id_tenant_fkey",
  },
  {
    child: "certificate_render_jobs",
    column: "certificate_id",
    parent: "certificates",
    name: "certificate_render_jobs_certificate_id_tenant_fkey",
  },
  {
    child: "payment_orders",
    column: "membership_id",
    parent: "memberships",
    name: "payment_orders_membership_id_tenant_fkey",
  },
  {
    child: "payment_instalments",
    column: "payment_order_id",
    parent: "payment_orders",
    name: "payment_instalments_payment_order_id_tenant_fkey",
  },
  {
    child: "payment_instalment_plans",
    column: "membership_id",
    parent: "memberships",
    name: "payment_instalment_plans_membership_id_tenant_fkey",
  },
  {
    child: "sales_coupon_redemptions",
    column: "coupon_id",
    parent: "sales_coupons",
    name: "sales_coupon_redemptions_coupon_id_tenant_fkey",
  },
  {
    child: "sales_coupon_redemptions",
    column: "payment_order_id",
    parent: "payment_orders",
    name: "sales_coupon_redemptions_payment_order_id_tenant_fkey",
  },
  {
    child: "sales_coupon_redemptions",
    column: "membership_id",
    parent: "memberships",
    name: "sales_coupon_redemptions_membership_id_tenant_fkey",
  },
  {
    child: "sales_coupon_redemptions",
    column: "course_id",
    parent: "courses",
    name: "sales_coupon_redemptions_course_id_tenant_fkey",
  },
  {
    child: "sales_coupon_courses",
    column: "coupon_id",
    parent: "sales_coupons",
    name: "sales_coupon_courses_coupon_id_tenant_fkey",
  },
  {
    child: "sales_coupon_courses",
    column: "course_id",
    parent: "courses",
    name: "sales_coupon_courses_course_id_tenant_fkey",
  },
  {
    child: "sales_wallets",
    column: "membership_id",
    parent: "memberships",
    name: "sales_wallets_membership_id_tenant_fkey",
  },
  {
    child: "sales_wallet_transactions",
    column: "wallet_id",
    parent: "sales_wallets",
    name: "sales_wallet_transactions_wallet_id_tenant_fkey",
  },
  {
    child: "sales_wallet_transactions",
    column: "payment_order_id",
    parent: "payment_orders",
    name: "sales_wallet_transactions_payment_order_id_tenant_fkey",
  },
  {
    child: "sales_wallet_transactions",
    column: "membership_id",
    parent: "memberships",
    name: "sales_wallet_transactions_membership_id_tenant_fkey",
  },
  {
    child: "sales_wallet_transactions",
    column: "course_id",
    parent: "courses",
    name: "sales_wallet_transactions_course_id_tenant_fkey",
  },
  {
    child: "sales_affiliate_commissions",
    column: "affiliate_id",
    parent: "sales_affiliates",
    name: "sales_affiliate_commissions_affiliate_id_tenant_fkey",
  },
  {
    child: "sales_affiliate_commissions",
    column: "payment_order_id",
    parent: "payment_orders",
    name: "sales_affiliate_commissions_payment_order_id_tenant_fkey",
  },
  {
    child: "sales_affiliate_commissions",
    column: "course_id",
    parent: "courses",
    name: "sales_affiliate_commissions_course_id_tenant_fkey",
  },
  {
    child: "sales_referral_purchase_credits",
    column: "payment_order_id",
    parent: "payment_orders",
    name: "sales_referral_purchase_credits_payment_order_id_tenant_fkey",
  },
  {
    child: "role_permissions",
    column: "role_id",
    parent: "roles",
    name: "role_permissions_role_id_tenant_fkey",
  },
  {
    child: "user_roles",
    column: "role_id",
    parent: "roles",
    name: "user_roles_role_id_tenant_fkey",
  },
  {
    child: "user_roles",
    column: "membership_id",
    parent: "memberships",
    name: "user_roles_membership_id_tenant_fkey",
  },
  {
    child: "permission_overrides",
    column: "membership_id",
    parent: "memberships",
    name: "permission_overrides_membership_id_tenant_fkey",
  },
];

/**
 * Every other reference whose parent is unambiguous (migrations 122 and 123).
 * Actor-attribution and polymorphic columns are deliberately not constrained;
 * see migration 122.
 */
export const COVERAGE_TENANT_FOREIGN_KEYS = [
  {
    child: "appeals",
    column: "moderation_case_id",
    parent: "moderation_cases",
    name: "appeals_moderation_case_id_tenant_fkey",
  },
  {
    child: "at_risk_alerts",
    column: "membership_id",
    parent: "memberships",
    name: "at_risk_alerts_membership_id_tenant_fkey",
  },
  {
    child: "attribution_tokens",
    column: "membership_id",
    parent: "memberships",
    name: "attribution_tokens_membership_id_tenant_fkey",
  },
  {
    child: "badge_awards",
    column: "badge_id",
    parent: "badges",
    name: "badge_awards_badge_id_tenant_fkey",
  },
  {
    child: "badge_awards",
    column: "membership_id",
    parent: "memberships",
    name: "badge_awards_membership_id_tenant_fkey",
  },
  {
    child: "batch_memberships",
    column: "membership_id",
    parent: "memberships",
    name: "batch_memberships_membership_id_tenant_fkey",
  },
  {
    child: "batches",
    column: "course_id",
    parent: "courses",
    name: "batches_course_id_tenant_fkey",
  },
  {
    child: "bundle_enrollments",
    column: "membership_id",
    parent: "memberships",
    name: "bundle_enrollments_membership_id_tenant_fkey",
  },
  {
    child: "certificates",
    column: "template_id",
    parent: "certificate_templates",
    name: "certificates_template_id_tenant_fkey",
  },
  {
    child: "comments",
    column: "author_membership_id",
    parent: "memberships",
    name: "comments_author_membership_id_tenant_fkey",
  },
  {
    child: "comments",
    column: "post_id",
    parent: "posts",
    name: "comments_post_id_tenant_fkey",
  },
  {
    child: "competency_bands",
    column: "scoring_profile_id",
    parent: "scoring_profiles",
    name: "competency_bands_scoring_profile_id_tenant_fkey",
  },
  {
    child: "competency_score_snapshots",
    column: "membership_id",
    parent: "memberships",
    name: "competency_score_snapshots_membership_id_tenant_fkey",
  },
  {
    child: "competency_score_snapshots",
    column: "scoring_profile_id",
    parent: "scoring_profiles",
    name: "competency_score_snapshots_scoring_profile_id_tenant_fkey",
  },
  {
    child: "competency_scores",
    column: "config_version_id",
    parent: "scoring_config_versions",
    name: "competency_scores_config_version_id_tenant_fkey",
  },
  {
    child: "competency_scores",
    column: "dimension_id",
    parent: "competency_dimensions",
    name: "competency_scores_dimension_id_tenant_fkey",
  },
  {
    child: "competency_scores",
    column: "membership_id",
    parent: "memberships",
    name: "competency_scores_membership_id_tenant_fkey",
  },
  {
    child: "competency_scores",
    column: "scoring_profile_id",
    parent: "scoring_profiles",
    name: "competency_scores_scoring_profile_id_tenant_fkey",
  },
  {
    child: "competency_signals",
    column: "dimension_id",
    parent: "competency_dimensions",
    name: "competency_signals_dimension_id_tenant_fkey",
  },
  {
    child: "competency_signals",
    column: "membership_id",
    parent: "memberships",
    name: "competency_signals_membership_id_tenant_fkey",
  },
  {
    child: "composite_readiness_state",
    column: "config_version_id",
    parent: "scoring_config_versions",
    name: "composite_readiness_state_config_version_id_tenant_fkey",
  },
  {
    child: "composite_readiness_state",
    column: "membership_id",
    parent: "memberships",
    name: "composite_readiness_state_membership_id_tenant_fkey",
  },
  {
    child: "composite_readiness_state",
    column: "scoring_profile_id",
    parent: "scoring_profiles",
    name: "composite_readiness_state_scoring_profile_id_tenant_fkey",
  },
  {
    child: "course_backup_jobs",
    column: "course_id",
    parent: "courses",
    name: "course_backup_jobs_course_id_tenant_fkey",
  },
  {
    child: "course_reviews",
    column: "course_id",
    parent: "courses",
    name: "course_reviews_course_id_tenant_fkey",
  },
  {
    child: "course_reviews",
    column: "membership_id",
    parent: "memberships",
    name: "course_reviews_membership_id_tenant_fkey",
  },
  {
    child: "course_tags",
    column: "course_id",
    parent: "courses",
    name: "course_tags_course_id_tenant_fkey",
  },
  {
    child: "course_tags",
    column: "tag_id",
    parent: "tags",
    name: "course_tags_tag_id_tenant_fkey",
  },
  {
    child: "custom_field_value_history",
    column: "membership_id",
    parent: "memberships",
    name: "custom_field_value_history_membership_id_tenant_fkey",
  },
  {
    child: "custom_field_values",
    column: "membership_id",
    parent: "memberships",
    name: "custom_field_values_membership_id_tenant_fkey",
  },
  {
    child: "dead_letter_events",
    column: "outbox_event_id",
    parent: "outbox_events",
    name: "dead_letter_events_outbox_event_id_tenant_fkey",
  },
  {
    child: "device_security_alerts",
    column: "membership_id",
    parent: "memberships",
    name: "device_security_alerts_membership_id_tenant_fkey",
  },
  {
    child: "device_sessions",
    column: "membership_id",
    parent: "memberships",
    name: "device_sessions_membership_id_tenant_fkey",
  },
  {
    child: "diagnostic_sessions",
    column: "assessment_id",
    parent: "assessments",
    name: "diagnostic_sessions_assessment_id_tenant_fkey",
  },
  {
    child: "diagnostic_sessions",
    column: "attempt_id",
    parent: "attempts",
    name: "diagnostic_sessions_attempt_id_tenant_fkey",
  },
  {
    child: "diagnostic_sessions",
    column: "membership_id",
    parent: "memberships",
    name: "diagnostic_sessions_membership_id_tenant_fkey",
  },
  {
    child: "event_deliveries",
    column: "outbox_event_id",
    parent: "outbox_events",
    name: "event_deliveries_outbox_event_id_tenant_fkey",
  },
  {
    child: "gamification_profiles",
    column: "membership_id",
    parent: "memberships",
    name: "gamification_profiles_membership_id_tenant_fkey",
  },
  {
    child: "grading_tasks",
    column: "assigned_to_membership_id",
    parent: "memberships",
    name: "grading_tasks_assigned_to_membership_id_tenant_fkey",
  },
  {
    child: "group_memberships",
    column: "membership_id",
    parent: "memberships",
    name: "group_memberships_membership_id_tenant_fkey",
  },
  {
    child: "group_memberships",
    column: "space_id",
    parent: "community_spaces",
    name: "group_memberships_space_id_tenant_fkey",
  },
  {
    child: "group_streak_states",
    column: "space_id",
    parent: "community_spaces",
    name: "group_streak_states_space_id_tenant_fkey",
  },
  {
    child: "identity_verifications",
    column: "membership_id",
    parent: "memberships",
    name: "identity_verifications_membership_id_tenant_fkey",
  },
  {
    child: "identity_verifications",
    column: "proctoring_session_id",
    parent: "proctoring_sessions",
    name: "identity_verifications_proctoring_session_id_tenant_fkey",
  },
  {
    child: "item_collection_items",
    column: "collection_id",
    parent: "item_collections",
    name: "item_collection_items_collection_id_tenant_fkey",
  },
  {
    child: "item_collection_items",
    column: "item_id",
    parent: "items",
    name: "item_collection_items_item_id_tenant_fkey",
  },
  {
    child: "item_dimension_weights",
    column: "dimension_id",
    parent: "competency_dimensions",
    name: "item_dimension_weights_dimension_id_tenant_fkey",
  },
  {
    child: "item_dimension_weights",
    column: "item_id",
    parent: "items",
    name: "item_dimension_weights_item_id_tenant_fkey",
  },
  {
    child: "item_statistics",
    column: "item_id",
    parent: "items",
    name: "item_statistics_item_id_tenant_fkey",
  },
  {
    child: "learner_subscription_enrollments",
    column: "membership_id",
    parent: "memberships",
    name: "learner_subscription_enrollments_membership_id_tenant_fkey",
  },
  {
    child: "lesson_tags",
    column: "lesson_id",
    parent: "lessons",
    name: "lesson_tags_lesson_id_tenant_fkey",
  },
  {
    child: "lesson_tags",
    column: "tag_id",
    parent: "tags",
    name: "lesson_tags_tag_id_tenant_fkey",
  },
  {
    child: "live_attendance",
    column: "membership_id",
    parent: "memberships",
    name: "live_attendance_membership_id_tenant_fkey",
  },
  {
    child: "live_sessions",
    column: "batch_id",
    parent: "batches",
    name: "live_sessions_batch_id_tenant_fkey",
  },
  {
    child: "live_sessions",
    column: "course_id",
    parent: "courses",
    name: "live_sessions_course_id_tenant_fkey",
  },
  {
    child: "marketing_ctas",
    column: "form_id",
    parent: "marketing_forms",
    name: "marketing_ctas_form_id_tenant_fkey",
  },
  {
    child: "marketing_event_registrations",
    column: "contact_id",
    parent: "marketing_contacts",
    name: "marketing_event_registrations_contact_id_tenant_fkey",
  },
  {
    child: "marketing_event_registrations",
    column: "event_id",
    parent: "marketing_events",
    name: "marketing_event_registrations_event_id_tenant_fkey",
  },
  {
    child: "marketing_event_registrations",
    column: "membership_id",
    parent: "memberships",
    name: "marketing_event_registrations_membership_id_tenant_fkey",
  },
  {
    child: "marketing_form_submissions",
    column: "contact_id",
    parent: "marketing_contacts",
    name: "marketing_form_submissions_contact_id_tenant_fkey",
  },
  {
    child: "marketing_form_submissions",
    column: "form_id",
    parent: "marketing_forms",
    name: "marketing_form_submissions_form_id_tenant_fkey",
  },
  {
    child: "marketing_integration_webhook_deliveries",
    column: "webhook_id",
    parent: "marketing_integration_webhooks",
    name: "marketing_integration_webhook_deliveries_webhook_id_tenant_fkey",
  },
  {
    child: "marketing_newsfeed_saves",
    column: "membership_id",
    parent: "memberships",
    name: "marketing_newsfeed_saves_membership_id_tenant_fkey",
  },
  {
    child: "marketing_newsfeed_saves",
    column: "post_id",
    parent: "marketing_newsfeed_posts",
    name: "marketing_newsfeed_saves_post_id_tenant_fkey",
  },
  {
    child: "marketing_promo_slides",
    column: "slider_id",
    parent: "marketing_promo_sliders",
    name: "marketing_promo_slides_slider_id_tenant_fkey",
  },
  {
    child: "marketing_workflow_run_logs",
    column: "run_id",
    parent: "marketing_workflow_runs",
    name: "marketing_workflow_run_logs_run_id_tenant_fkey",
  },
  {
    child: "marketing_workflow_runs",
    column: "membership_id",
    parent: "memberships",
    name: "marketing_workflow_runs_membership_id_tenant_fkey",
  },
  {
    child: "marketing_workflow_runs",
    column: "workflow_id",
    parent: "marketing_workflows",
    name: "marketing_workflow_runs_workflow_id_tenant_fkey",
  },
  {
    child: "member_balances",
    column: "membership_id",
    parent: "memberships",
    name: "member_balances_membership_id_tenant_fkey",
  },
  {
    child: "mentions",
    column: "mentioned_membership_id",
    parent: "memberships",
    name: "mentions_mentioned_membership_id_tenant_fkey",
  },
  {
    child: "messenger_messages",
    column: "sender_membership_id",
    parent: "memberships",
    name: "messenger_messages_sender_membership_id_tenant_fkey",
  },
  {
    child: "mock_test_enrollments",
    column: "membership_id",
    parent: "memberships",
    name: "mock_test_enrollments_membership_id_tenant_fkey",
  },
  {
    child: "mock_tests",
    column: "assessment_id",
    parent: "assessments",
    name: "mock_tests_assessment_id_tenant_fkey",
  },
  {
    child: "moderation_decisions",
    column: "moderation_case_id",
    parent: "moderation_cases",
    name: "moderation_decisions_moderation_case_id_tenant_fkey",
  },
  {
    child: "module_scorm_progress",
    column: "membership_id",
    parent: "memberships",
    name: "module_scorm_progress_membership_id_tenant_fkey",
  },
  {
    child: "module_scorm_progress",
    column: "module_id",
    parent: "course_modules",
    name: "module_scorm_progress_module_id_tenant_fkey",
  },
  {
    child: "notification_dispatches",
    column: "membership_id",
    parent: "memberships",
    name: "notification_dispatches_membership_id_tenant_fkey",
  },
  {
    child: "path_enrollments",
    column: "membership_id",
    parent: "memberships",
    name: "path_enrollments_membership_id_tenant_fkey",
  },
  {
    child: "path_enrollments",
    column: "path_id",
    parent: "learning_paths",
    name: "path_enrollments_path_id_tenant_fkey",
  },
  {
    child: "path_step_gates",
    column: "path_step_id",
    parent: "path_steps",
    name: "path_step_gates_path_step_id_tenant_fkey",
  },
  {
    child: "path_step_progress",
    column: "membership_id",
    parent: "memberships",
    name: "path_step_progress_membership_id_tenant_fkey",
  },
  {
    child: "path_steps",
    column: "path_id",
    parent: "learning_paths",
    name: "path_steps_path_id_tenant_fkey",
  },
  {
    child: "payment_gateways",
    column: "billing_location_id",
    parent: "learner_billing_locations",
    name: "payment_gateways_billing_location_id_tenant_fkey",
  },
  {
    child: "payment_refund_intents",
    column: "gateway_id",
    parent: "payment_gateways",
    name: "payment_refund_intents_gateway_id_tenant_fkey",
  },
  {
    child: "point_ledger",
    column: "membership_id",
    parent: "memberships",
    name: "point_ledger_membership_id_tenant_fkey",
  },
  {
    child: "poll_responses",
    column: "membership_id",
    parent: "memberships",
    name: "poll_responses_membership_id_tenant_fkey",
  },
  {
    child: "polls",
    column: "live_session_id",
    parent: "live_sessions",
    name: "polls_live_session_id_tenant_fkey",
  },
  {
    child: "posts",
    column: "author_membership_id",
    parent: "memberships",
    name: "posts_author_membership_id_tenant_fkey",
  },
  {
    child: "posts",
    column: "space_id",
    parent: "community_spaces",
    name: "posts_space_id_tenant_fkey",
  },
  {
    child: "practice_responses",
    column: "item_id",
    parent: "items",
    name: "practice_responses_item_id_tenant_fkey",
  },
  {
    child: "practice_responses",
    column: "membership_id",
    parent: "memberships",
    name: "practice_responses_membership_id_tenant_fkey",
  },
  {
    child: "practice_responses",
    column: "practice_session_id",
    parent: "practice_sessions",
    name: "practice_responses_practice_session_id_tenant_fkey",
  },
  {
    child: "practice_sessions",
    column: "collection_id",
    parent: "item_collections",
    name: "practice_sessions_collection_id_tenant_fkey",
  },
  {
    child: "practice_sessions",
    column: "membership_id",
    parent: "memberships",
    name: "practice_sessions_membership_id_tenant_fkey",
  },
  {
    child: "proctoring_reports",
    column: "proctoring_session_id",
    parent: "proctoring_sessions",
    name: "proctoring_reports_proctoring_session_id_tenant_fkey",
  },
  {
    child: "quest_definitions",
    column: "course_id",
    parent: "courses",
    name: "quest_definitions_course_id_tenant_fkey",
  },
  {
    child: "quest_progress",
    column: "membership_id",
    parent: "memberships",
    name: "quest_progress_membership_id_tenant_fkey",
  },
  {
    child: "reactions",
    column: "membership_id",
    parent: "memberships",
    name: "reactions_membership_id_tenant_fkey",
  },
  {
    child: "readiness_policies",
    column: "scoring_profile_id",
    parent: "scoring_profiles",
    name: "readiness_policies_scoring_profile_id_tenant_fkey",
  },
  {
    child: "report_delivery_effects",
    column: "destination_id",
    parent: "report_delivery_destinations",
    name: "report_delivery_effects_destination_id_tenant_fkey",
  },
  {
    child: "reward_redemptions",
    column: "membership_id",
    parent: "memberships",
    name: "reward_redemptions_membership_id_tenant_fkey",
  },
  {
    child: "reward_redemptions",
    column: "reward_item_id",
    parent: "reward_items",
    name: "reward_redemptions_reward_item_id_tenant_fkey",
  },
  {
    child: "sales_affiliate_commissions",
    column: "affiliate_membership_id",
    parent: "memberships",
    name: "sales_affiliate_commissions_affiliate_membership_id_tenant_fkey",
  },
  {
    child: "sales_affiliate_commissions",
    column: "buyer_membership_id",
    parent: "memberships",
    name: "sales_affiliate_commissions_buyer_membership_id_tenant_fkey",
  },
  {
    child: "sales_affiliate_commissions",
    column: "payout_id",
    parent: "sales_affiliate_payouts",
    name: "sales_affiliate_commissions_payout_id_tenant_fkey",
  },
  {
    child: "sales_affiliate_payouts",
    column: "affiliate_id",
    parent: "sales_affiliates",
    name: "sales_affiliate_payouts_affiliate_id_tenant_fkey",
  },
  {
    child: "sales_affiliate_payouts",
    column: "affiliate_membership_id",
    parent: "memberships",
    name: "sales_affiliate_payouts_affiliate_membership_id_tenant_fkey",
  },
  {
    child: "sales_affiliate_products",
    column: "course_id",
    parent: "courses",
    name: "sales_affiliate_products_course_id_tenant_fkey",
  },
  {
    child: "sales_affiliate_requests",
    column: "membership_id",
    parent: "memberships",
    name: "sales_affiliate_requests_membership_id_tenant_fkey",
  },
  {
    child: "sales_affiliates",
    column: "membership_id",
    parent: "memberships",
    name: "sales_affiliates_membership_id_tenant_fkey",
  },
  {
    child: "sales_attribution_events",
    column: "membership_id",
    parent: "memberships",
    name: "sales_attribution_events_membership_id_tenant_fkey",
  },
  {
    child: "sales_referral_attributions",
    column: "referee_membership_id",
    parent: "memberships",
    name: "sales_referral_attributions_referee_membership_id_tenant_fkey",
  },
  {
    child: "sales_referral_attributions",
    column: "referral_code_id",
    parent: "sales_referral_codes",
    name: "sales_referral_attributions_referral_code_id_tenant_fkey",
  },
  {
    child: "sales_referral_attributions",
    column: "referrer_membership_id",
    parent: "memberships",
    name: "sales_referral_attributions_referrer_membership_id_tenant_fkey",
  },
  {
    child: "sales_referral_codes",
    column: "membership_id",
    parent: "memberships",
    name: "sales_referral_codes_membership_id_tenant_fkey",
  },
  {
    child: "sales_referral_purchase_credits",
    column: "attribution_id",
    parent: "sales_referral_attributions",
    name: "sales_referral_purchase_credits_attribution_id_tenant_fkey",
  },
  {
    child: "sales_referral_purchase_credits",
    column: "referee_membership_id",
    parent: "memberships",
    name: "sales_referral_purchase_credits_referee_membership_tenant_fkey",
  },
  {
    child: "sales_referral_purchase_credits",
    column: "referrer_membership_id",
    parent: "memberships",
    name: "sales_referral_purchase_credits_referrer_membership_tenant_fkey",
  },
  {
    child: "scoring_config_versions",
    column: "scoring_profile_id",
    parent: "scoring_profiles",
    name: "scoring_config_versions_scoring_profile_id_tenant_fkey",
  },
  {
    child: "srs_state",
    column: "item_id",
    parent: "items",
    name: "srs_state_item_id_tenant_fkey",
  },
  {
    child: "srs_state",
    column: "membership_id",
    parent: "memberships",
    name: "srs_state_membership_id_tenant_fkey",
  },
  {
    child: "streak_freezes",
    column: "membership_id",
    parent: "memberships",
    name: "streak_freezes_membership_id_tenant_fkey",
  },
  {
    child: "streak_states",
    column: "membership_id",
    parent: "memberships",
    name: "streak_states_membership_id_tenant_fkey",
  },
  {
    child: "tenant_active_days",
    column: "membership_id",
    parent: "memberships",
    name: "tenant_active_days_membership_id_tenant_fkey",
  },
  {
    child: "test_series_enrollments",
    column: "membership_id",
    parent: "memberships",
    name: "test_series_enrollments_membership_id_tenant_fkey",
  },
  {
    child: "test_series_item_progress",
    column: "attempt_id",
    parent: "attempts",
    name: "test_series_item_progress_attempt_id_tenant_fkey",
  },
  {
    child: "test_series_item_progress",
    column: "membership_id",
    parent: "memberships",
    name: "test_series_item_progress_membership_id_tenant_fkey",
  },
  {
    child: "test_series_items",
    column: "assessment_id",
    parent: "assessments",
    name: "test_series_items_assessment_id_tenant_fkey",
  },
  {
    child: "test_series_items",
    column: "mock_test_id",
    parent: "mock_tests",
    name: "test_series_items_mock_test_id_tenant_fkey",
  },
  {
    child: "whatsapp_campaigns",
    column: "template_id",
    parent: "whatsapp_templates",
    name: "whatsapp_campaigns_template_id_tenant_fkey",
  },
  {
    child: "whatsapp_conversations",
    column: "membership_id",
    parent: "memberships",
    name: "whatsapp_conversations_membership_id_tenant_fkey",
  },
  {
    child: "whatsapp_inbox_messages",
    column: "conversation_id",
    parent: "whatsapp_conversations",
    name: "whatsapp_inbox_messages_conversation_id_tenant_fkey",
  },
  {
    child: "workflow_transitions",
    column: "workflow_definition_id",
    parent: "workflow_definitions",
    name: "workflow_transitions_workflow_definition_id_tenant_fkey",
  },
  {
    child: "zoom_meeting_participants",
    column: "membership_id",
    parent: "memberships",
    name: "zoom_meeting_participants_membership_id_tenant_fkey",
  },
  {
    child: "zoom_webhook_events",
    column: "zoom_connection_id",
    parent: "zoom_connections",
    name: "zoom_webhook_events_zoom_connection_id_tenant_fkey",
  },
];

export const TENANT_FOREIGN_KEYS = [...CORE_TENANT_FOREIGN_KEYS, ...COVERAGE_TENANT_FOREIGN_KEYS];
