packages:
  - "apps/*"
  - "packages/*"
  - "packages/domain/config"
  - "packages/domain/tenancy"
  - "packages/domain/branding"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
