import {
  Award,
  BadgeCheck,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  Building2,
  ClipboardCheck,
  Cog,
  CreditCard,
  Database,
  FileText,
  Gauge,
  Globe,
  GraduationCap,
  KeyRound,
  Languages,
  Layers,
  Mail,
  MessagesSquare,
  Palette,
  PlayCircle,
  Puzzle,
  Receipt,
  ScrollText,
  Search,
  ShieldCheck,
  Sparkles,
  Trophy,
  Users,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { KnownEntitlementKey } from "../../entitlements/entitlement-catalogue";
import type { FeatureMotif } from "./FeaturePreview";

export type FeatureGroup = {
  id: string;
  label: string;
  description: string;
  icon: LucideIcon;
};

export type FeatureEntry = {
  id: string;
  groupId: string;
  name: string;
  blurb: string;
  icon: LucideIcon;
  motif: FeatureMotif;
  accentToken: string;
  /** Destination when the admin opens/configures this feature, if one exists. */
  href?: string;
  /** When set, the card shows live Active / Not-in-plan status from entitlements. */
  entitlementKey?: KnownEntitlementKey;
};

export const FEATURE_GROUPS: readonly FeatureGroup[] = [
  {
    id: "authoring",
    label: "Course creation & delivery",
    description: "Build, structure, and deliver learning content.",
    icon: GraduationCap,
  },
  {
    id: "engagement",
    label: "Learner engagement",
    description: "Keep learners motivated, connected, and progressing.",
    icon: Sparkles,
  },
  {
    id: "administration",
    label: "Administration & operations",
    description: "Run your academy: people, security, insights, and automation.",
    icon: Cog,
  },
  {
    id: "monetisation",
    label: "Billing & payments",
    description: "Sell courses and manage learner billing end to end.",
    icon: CreditCard,
  },
] as const;

export const FEATURE_CATALOGUE: readonly FeatureEntry[] = [
  // Course creation & delivery
  {
    id: "courses",
    groupId: "authoring",
    name: "Courses",
    blurb: "Author multi-module courses with drip scheduling and prerequisites.",
    icon: BookOpen,
    motif: "list",
    accentToken: "--admin-lesson-scorm",
    href: "/studio/courses",
  },
  {
    id: "lessons",
    groupId: "authoring",
    name: "Rich Lessons",
    blurb: "Mix video, audio, PDF, slides, SCORM, articles, and live sessions.",
    icon: PlayCircle,
    motif: "player",
    accentToken: "--admin-lesson-video",
    href: "/studio/courses",
  },
  {
    id: "assessments",
    groupId: "authoring",
    name: "Assessments",
    blurb: "Create quizzes and exams with question banks and auto-grading.",
    icon: ClipboardCheck,
    motif: "quiz",
    accentToken: "--admin-lesson-quiz",
    href: "/studio/assessments",
  },
  {
    id: "learning-paths",
    groupId: "authoring",
    name: "Learning Paths",
    blurb: "Sequence courses into guided journeys toward a goal.",
    icon: Workflow,
    motif: "path",
    accentToken: "--admin-lesson-live",
    href: "/studio/learning-paths",
  },
  {
    id: "grading",
    groupId: "authoring",
    name: "Grading",
    blurb: "Review submissions, score work, and return feedback at scale.",
    icon: BadgeCheck,
    motif: "chart",
    accentToken: "--admin-lesson-assignment",
    href: "/studio/grading",
  },
  {
    id: "item-bank",
    groupId: "authoring",
    name: "Item Bank",
    blurb: "Reusable question and content items organised into collections.",
    icon: Boxes,
    motif: "grid",
    accentToken: "--admin-lesson-audio",
    href: "/studio/items",
  },
  {
    id: "competency",
    groupId: "authoring",
    name: "Competency",
    blurb: "Map content to skills and track mastery across your catalogue.",
    icon: Gauge,
    motif: "ring",
    accentToken: "--admin-lesson-slides",
    href: "/admin/competency",
  },

  // Learner engagement
  {
    id: "community",
    groupId: "engagement",
    name: "Community Spaces",
    blurb: "Give learners a place to connect, ask questions, and learn together.",
    icon: MessagesSquare,
    motif: "chat",
    accentToken: "--admin-lesson-live",
    entitlementKey: "community.enable",
  },
  {
    id: "private-spaces",
    groupId: "engagement",
    name: "Private Spaces",
    blurb: "Invite-only spaces for cohorts, premium tiers, or mentor groups.",
    icon: KeyRound,
    motif: "shield",
    accentToken: "--admin-lesson-quiz",
    entitlementKey: "community.private_spaces.enable",
  },
  {
    id: "certification",
    groupId: "engagement",
    name: "Certification",
    blurb: "Issue branded, verifiable certificates on course completion.",
    icon: Award,
    motif: "certificate",
    accentToken: "--admin-lesson-slides",
    href: "/admin/certificates",
    entitlementKey: "certification.enable",
  },
  {
    id: "gamification",
    groupId: "engagement",
    name: "Gamification",
    blurb: "Points, badges, and leaderboards that keep learners coming back.",
    icon: Trophy,
    motif: "trophy",
    accentToken: "--admin-lesson-audio",
    href: "/admin/gamification",
    entitlementKey: "gamification.enable",
  },
  {
    id: "readiness",
    groupId: "engagement",
    name: "Readiness",
    blurb: "Gate progress on readiness checks so learners advance when ready.",
    icon: Gauge,
    motif: "ring",
    accentToken: "--admin-lesson-scorm",
    href: "/admin/readiness-policy",
  },

  // Administration & operations
  {
    id: "members",
    groupId: "administration",
    name: "Members",
    blurb: "Manage learners and staff, invitations, and account lifecycle.",
    icon: Users,
    motif: "people",
    accentToken: "--admin-lesson-scorm",
    href: "/admin/members",
  },
  {
    id: "roles",
    groupId: "administration",
    name: "Roles & Permissions",
    blurb: "Fine-grained, role-based access control across every surface.",
    icon: ShieldCheck,
    motif: "shield",
    accentToken: "--admin-lesson-assignment",
    href: "/admin/roles",
  },
  {
    id: "branding",
    groupId: "administration",
    name: "Branding",
    blurb: "Make the academy yours with logo, colours, and theme controls.",
    icon: Palette,
    motif: "palette",
    accentToken: "--admin-lesson-live",
    href: "/admin/branding",
  },
  {
    id: "custom-domain",
    groupId: "administration",
    name: "Custom Domain",
    blurb: "Host your academy on your own fully branded domain.",
    icon: Globe,
    motif: "globe",
    accentToken: "--admin-lesson-scorm",
    href: "/admin/domains",
    entitlementKey: "branding.custom_domain.enable",
  },
  {
    id: "analytics",
    groupId: "administration",
    name: "Analytics",
    blurb: "Live dashboards for enrolments, progress, and completion.",
    icon: BarChart3,
    motif: "chart",
    accentToken: "--admin-lesson-video",
    href: "/admin/analytics",
    entitlementKey: "analytics.dashboard.view",
  },
  {
    id: "data-export",
    groupId: "administration",
    name: "Data Export",
    blurb: "Bulk-export learners, progress, and revenue for your own tools.",
    icon: Database,
    motif: "download",
    accentToken: "--admin-lesson-audio",
    href: "/admin/exports",
    entitlementKey: "data.export.enable",
  },
  {
    id: "seo",
    groupId: "administration",
    name: "SEO",
    blurb: "Control metadata and discoverability for public course pages.",
    icon: Search,
    motif: "search",
    accentToken: "--admin-lesson-slides",
    href: "/admin/seo",
  },
  {
    id: "notifications",
    groupId: "administration",
    name: "Notifications",
    blurb: "Reach learners with templated, multi-channel notifications.",
    icon: Bell,
    motif: "bell",
    accentToken: "--admin-lesson-live",
    href: "/admin/notifications",
  },
  {
    id: "email-channels",
    groupId: "administration",
    name: "Email Channels",
    blurb: "Configure transactional, marketing, and support email delivery.",
    icon: Mail,
    motif: "envelope",
    accentToken: "--admin-lesson-quiz",
    href: "/admin/channels/transactional-email",
  },
  {
    id: "automation",
    groupId: "administration",
    name: "Automation",
    blurb: "Trigger actions automatically from learner and account events.",
    icon: Zap,
    motif: "path",
    accentToken: "--admin-lesson-assignment",
    href: "/admin/automation",
  },
  {
    id: "workflows",
    groupId: "administration",
    name: "Workflows",
    blurb: "Model review and approval flows for content and operations.",
    icon: Layers,
    motif: "path",
    accentToken: "--admin-lesson-video",
    href: "/admin/workflows",
  },
  {
    id: "moderation",
    groupId: "administration",
    name: "Moderation",
    blurb: "Handle reports, cases, and appeals to keep community safe.",
    icon: ShieldCheck,
    motif: "shield",
    accentToken: "--admin-lesson-pdf",
    href: "/admin/moderation/cases",
  },
  {
    id: "security",
    groupId: "administration",
    name: "Security",
    blurb: "Admin OTP, device monitoring, and learner email verification.",
    icon: KeyRound,
    motif: "shield",
    accentToken: "--admin-lesson-scorm",
    href: "/admin/security/admin-otp",
  },
  {
    id: "locales",
    groupId: "administration",
    name: "Localisation",
    blurb: "Serve your academy in multiple languages and locales.",
    icon: Languages,
    motif: "globe",
    accentToken: "--admin-lesson-audio",
    href: "/admin/locales",
  },
  {
    id: "audit",
    groupId: "administration",
    name: "Audit Log",
    blurb: "A tamper-evident trail of every sensitive action taken.",
    icon: ScrollText,
    motif: "list",
    accentToken: "--admin-lesson-article",
    href: "/admin/audit",
  },
  {
    id: "extensions",
    groupId: "administration",
    name: "Extensions",
    blurb: "Extend the platform with registered extension points.",
    icon: Puzzle,
    motif: "grid",
    accentToken: "--admin-lesson-quiz",
    href: "/admin/extensions",
  },

  // Billing & payments
  {
    id: "pricing",
    groupId: "monetisation",
    name: "Pricing Model",
    blurb: "Free, one-time, or subscription pricing for your courses.",
    icon: CreditCard,
    motif: "card",
    accentToken: "--admin-lesson-video",
    href: "/admin/learner-billing/pricing-model",
  },
  {
    id: "payment-gateway",
    groupId: "monetisation",
    name: "Payment Gateway",
    blurb: "Connect your gateway to collect payments from learners.",
    icon: Building2,
    motif: "card",
    accentToken: "--admin-lesson-scorm",
    href: "/admin/learner-billing/payment-gateway",
  },
  {
    id: "invoicing",
    groupId: "monetisation",
    name: "Invoicing & Tax",
    blurb: "Automated invoices, GST/tax handling, and billing addresses.",
    icon: Receipt,
    motif: "receipt",
    accentToken: "--admin-lesson-slides",
    href: "/admin/learner-billing/invoice-config",
  },
  {
    id: "fast-checkout",
    groupId: "monetisation",
    name: "Fast Checkout",
    blurb: "A streamlined, high-converting checkout for your learners.",
    icon: FileText,
    motif: "receipt",
    accentToken: "--admin-lesson-live",
    href: "/admin/fast-checkout",
  },
] as const;
