export { EntitlementLimitExceededError, EntitlementRequiredError } from "@atlas/authorization";
export const STORAGE_ERROR_CODES = {
  ASSET_REFERENCE_NOT_FOUND: "ASSET_REFERENCE_NOT_FOUND",
  ASSET_OBJECT_NOT_FOUND: "ASSET_OBJECT_NOT_FOUND",
  ASSET_SIZE_LIMIT_EXCEEDED: "ASSET_SIZE_LIMIT_EXCEEDED",
  UNSUPPORTED_BRANDING_ASSET_TYPE: "UNSUPPORTED_BRANDING_ASSET_TYPE",
  UNSUPPORTED_LESSON_ASSET_TYPE: "UNSUPPORTED_LESSON_ASSET_TYPE",
  SELF_HOSTED_VIDEO_FORBIDDEN: "SELF_HOSTED_VIDEO_FORBIDDEN",
  STORAGE_KEY_TENANT_PREFIX_VIOLATION: "STORAGE_KEY_TENANT_PREFIX_VIOLATION",
  ASSET_CONTENT_TYPE_MISMATCH: "ASSET_CONTENT_TYPE_MISMATCH",
  ASSET_SIZE_MISMATCH: "ASSET_SIZE_MISMATCH",
  ASSET_CHECKSUM_MISMATCH: "ASSET_CHECKSUM_MISMATCH",
  INVALID_SHA256_CHECKSUM: "INVALID_SHA256_CHECKSUM",
  VIDEO_PROVIDER_HOST_MISMATCH: "VIDEO_PROVIDER_HOST_MISMATCH",
} as const;
