"use client";

import {
  AtSign,
  Award,
  Banknote,
  BarChart3,
  Bell,
  CircleDollarSign,
  Clock,
  CreditCard,
  Download,
  FileBadge,
  FileText,
  Flag,
  FolderCog,
  GitBranch,
  Globe,
  Globe2,
  KeyRound,
  Languages,
  Mail,
  MailCheck,
  MailOpen,
  MapPin,
  MonitorPlay,
  Palette,
  Puzzle,
  Receipt,
  ScrollText,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Target,
  Trash2,
  Trophy,
  Users,
  UserLock,
  WalletCards,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { AdminSettingsIconKey } from "./admin-settings-catalog";

const ADMIN_SETTINGS_ICONS: Record<AdminSettingsIconKey, LucideIcon> = {
  "settings-2": Settings2,
  flag: Flag,
  "key-round": KeyRound,
  languages: Languages,
  palette: Palette,
  globe: Globe,
  target: Target,
  award: Award,
  trophy: Trophy,
  "file-badge": FileBadge,
  puzzle: Puzzle,
  zap: Zap,
  users: Users,
  "scroll-text": ScrollText,
  "trash-2": Trash2,
  download: Download,
  "shield-check": ShieldCheck,
  bell: Bell,
  "git-branch": GitBranch,
  "bar-chart-3": BarChart3,
  "credit-card": CreditCard,
  "globe-2": Globe2,
  clock: Clock,
  "monitor-play": MonitorPlay,
  banknote: Banknote,
  "circle-dollar-sign": CircleDollarSign,
  "wallet-cards": WalletCards,
  receipt: Receipt,
  "folder-cog": FolderCog,
  "file-text": FileText,
  "map-pin": MapPin,
  "shopping-cart": ShoppingCart,
  "mail-check": MailCheck,
  "user-lock": UserLock,
  smartphone: Smartphone,
  mail: Mail,
  "mail-open": MailOpen,
  "at-sign": AtSign,
};

export function adminSettingsIcon(key: AdminSettingsIconKey): LucideIcon {
  return ADMIN_SETTINGS_ICONS[key];
}
