export const APPROVED_EVENT_TYPES = new Set<string>([
  "tenant.created",
  "tenant.state_changed",
  "membership.created",
  "membership.status_changed",
  "role.assigned",
  "role.revoked",
  "permission.changed",
  "entitlement.changed",
  "config.branding.published",
  "config.theme.published",
  "domain.changed",
  "course.submitted_for_review",
  "course.published",
  "workflow.transitioned",
  "learning.enrollment.created",
  "lesson.completed",
  "path.step_completed",
  "assessment.started",
  "assessment.submitted",
  "assessment.graded",
  "practice.session_completed",
  "competency.signal_recorded",
  "competency.score_changed",
  "readiness.band_changed",
  "certificate.issued",
  "certificate.revoked",
  "badge.awarded",
  "streak.updated",
  "community.post.created",
  "community.comment.created",
  "moderation.reported",
  "moderation.decided",
  "notification.requested",
  "notification.queued",
  "search.reindex_requested",
  "analytics.projection_requested",
  "data.export_requested",
  "data.deletion_requested",
]);

export function assertApprovedEventType(eventType: string): void {
  if (!APPROVED_EVENT_TYPES.has(eventType)) {
    throw new Error(`Unapproved outbox event type: ${eventType}`);
  }
}
