import { PERMISSIONS } from "./permission-catalogue";
import type { TenantSystemRoleKey } from "./tenant-system-roles";

const TENANT_CATALOGUE_PERMISSIONS = PERMISSIONS.filter(
  (permission) => !permission.platformOnly,
).map((permission) => permission.key);

export const ROLE_PERMISSIONS: Record<TenantSystemRoleKey, readonly string[]> = {
  owner: TENANT_CATALOGUE_PERMISSIONS,
  admin: TENANT_CATALOGUE_PERMISSIONS,

  instructor: [
    "profile.read",
    "profile.update",
    "course.read",
    "course.create",
    "course.update",
    "course.delete",
    "course.publish",
    "enrollment.read",
    "progress.read",
    "learning_path.read",
    "learning_path.create",
    "learning_path.update",
    "learning_path.delete",
    "learning_path.publish",
    "item.read",
    "item.create",
    "item.update",
    "item.delete",
    "item_collection.manage",
    "assessment.read",
    "assessment.create",
    "assessment.update",
    "assessment.delete",
    "assessment.publish",
    "assessment.grade",
    "attempt.read",
    "competency.dimension.read",
    "scoring_profile.read",
    "competency.score.read",
    "certificate_template.read",
    "certificate.read",
    "certificate.issue",
    "gamification.profile.read",
    "badge.read",
    "leaderboard.read",
    "community.space.read",
    "community.space.join",
    "post.read",
    "post.create",
    "comment.create",
    "reaction.create",
    "appeal.create",
    "notification.read.self",
    "search.query",
    "workflow.definition.read",
    "workflow.transition.act",
    "automation.rule.read",
    "locale.read",
    "extension.point.read",
    "extension.registration.read",
    "diagnostic.start",
    "readiness_policy.read",
  ],

  moderator: [
    "profile.read",
    "profile.update",
    "badge.read",
    "leaderboard.read",
    "community.space.read",
    "community.space.manage",
    "community.space.join",
    "post.read",
    "post.create",
    "post.update",
    "post.delete",
    "comment.create",
    "comment.update",
    "comment.delete",
    "reaction.create",
    "community.moderate",
    "appeal.review",
    "notification.read.self",
    "search.query",
    "workflow.transition.act",
    "locale.read",
    "diagnostic.start",
  ],

  learner: [
    "profile.read",
    "profile.update",
    "course.read",
    "enrollment.read",
    "enrollment.create",
    "progress.read",
    "learning_path.read",
    "assessment.read",
    "attempt.start",
    "attempt.submit",
    "attempt.read",
    "practice.start",
    "competency.score.read",
    "certificate.read",
    "gamification.profile.read",
    "badge.read",
    "leaderboard.read",
    "community.space.read",
    "community.space.join",
    "post.read",
    "post.create",
    "post.update",
    "post.delete",
    "comment.create",
    "comment.update",
    "comment.delete",
    "reaction.create",
    "appeal.create",
    "notification.read.self",
    "search.query",
    "locale.read",
    "diagnostic.start",
    "readiness_policy.read",
    "data.deletion.request",
  ],
} as const;
