/** Synthetic values only. These fixtures never connect to a provider. */
export function deploymentEnv(): NodeJS.ProcessEnv {
  return {
    NODE_ENV: "production",
    APP_ENV: "production",
    NEXT_RUNTIME: "nodejs",
    ATLAS_SERVICE_RUNTIME: "managed-node",
    VERCEL: "",
    VERCEL_ENV: "",
    RELEASE_ENV: "production",
    RATE_LIMIT_REDIS_URL: "rediss://redis.example.test:6380",
    REDIS_URL: "",
    TRUSTED_PROXY_HOPS: "1",
    TRUSTED_CLIENT_IP_HEADER: "",
    STORAGE_PROVIDER: "r2",
    R2_ACCOUNT_ID: "a1b2c3d4e5f60718293a4b5c6d7e8f90",
    R2_ACCESS_KEY_ID: "synthetic-access-key",
    R2_SECRET_ACCESS_KEY: "synthetic-private-storage-key",
    R2_BUCKET_NAME: "atlas-test-assets",
    STORAGE_LOCAL_SIGNING_SECRET: "",
    DATABASE_URL:
      "postgresql://atlas_app_login:synthetic-password@db.example.test:5432/atlas?sslmode=require",
    PLATFORM_DATABASE_URL:
      "postgresql://atlas_platform_login:synthetic-password@db.example.test:5432/atlas?sslmode=require",
    APP_URL: "https://learn.example.test",
    PLATFORM_HOST: "platform.example.test",
    API_INTERNAL_URL: "https://api.example.test",
    PUBLIC_SITE_URL: "",
    CERTIFICATE_PUBLIC_BASE_URL: "https://learn.example.test",
    NEXT_PUBLIC_SUPABASE_URL: "https://auth.example.test",
    NEXT_PUBLIC_SUPABASE_ANON_KEY: "sb_publishable_synthetic-public-key",
    SUPABASE_SERVICE_ROLE_KEY: "synthetic-private-auth-key",
    CRON_SECRET: "f270994c918cdbe90b3a847736cdd189612d49275e39e58b",
    INTERNAL_WORKER_SECRET: "ae352175d723ab180457b68256a69d3f1abe7d330c640aeb",
    API_PROXY_SECRET: "36f54a9e62e782e52ca45d21d8b5d7b894c181b9aad08a73",
    LEARNER_BILLING_ENC_KEY: Buffer.from("0123456789abcdefFEDCBA9876543210").toString("base64"),
    OBSERVABILITY_HASH_SALT: "ba379df16024636e8da39d52d539092096412378beb0ae78",
    NOTIFICATION_EMAIL_PROVIDER: "smtp",
    SMTP_HOST: "smtp.example.test",
    SMTP_PORT: "587",
    SMTP_USER: "synthetic-user",
    SMTP_PASSWORD: "synthetic-mail-password",
    NOTIFICATION_EMAIL_FROM: "Atlas <noreply@example.test>",
    SENTRY_DSN: "https://synthetic@sentry.example.test/1",
    NEXT_PUBLIC_SENTRY_DSN: "",
    SENTRY_TRACES_SAMPLE_RATE: "0.05",
    RELEASE_SHA: "ca8c0f1e7e69780b4e2ddc2a1136907a2e47c350",
    RELEASE_VERSION: "",
    BETTER_STACK_WORKER_HEARTBEAT_URL: "https://heartbeat.example.test/synthetic",
    CERTIFICATE_OPEN_BADGE: "false",
    CERTIFICATE_WALLETS: "false",
    CERTIFICATE_BLOCKCHAIN_ANCHOR: "false",
  };
}
